url1<-("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip")
download.file(url1, "./data/household_power_consumption.zip", method="curl")
unzip("./data/household_power_consumption.zip")
power <- read.table("household_power_consumption.txt", header = T, sep=";", comment.char="%", stringsAsFactors=FALSE, na.strings="?") 
library(lubridate)
power$Date<-dmy(power$Date)
##power$Time<-hms(power$Time)
power12<-subset(power, power$Date >= "2007-01-31" & power$Date <= "2007-02-02")
power12$Global_active_power<-as.numeric(power12$Global_active_power)
power12 <- transform(power12, timestamp=as.POSIXct(paste(Date, Time)), "%Y-%m-%d %H:%M:%S")
plot(power12$timestamp, power12$Global_active_power, ylab="Global Active Power (kilowatts)", xlab="", type="l")
dev.copy(png, file="plot2.png")
dev.off()