url1<-("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip")
download.file(url1, "./data/household_power_consumption.zip", method="curl")
unzip("./data/household_power_consumption.zip")
power <- read.table("household_power_consumption.txt", header = T, sep=";", comment.char="%", stringsAsFactors=FALSE, na.strings="?") 
library(lubridate)
power$Date<-dmy(power$Date)
##power$Time<-hms(power$Time)
power12<-subset(power, power$Date >= "2007-01-31" & power$Date <= "2007-02-02")
power12$Global_active_power<-as.numeric(power12$Global_active_power)
hist(power12$Global_active_power, main="Global Active Power", xlab="Global Active Power (kilowatts)", col="red")
dev.copy(png, file="plot1.png")
dev.off()
